// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ssGP
Rcpp::NumericMatrix ssGP(Rcpp::NumericMatrix baseline, Rcpp::NumericMatrix mixture, Rcpp::NumericMatrix crossRecords, Rcpp::List baselineParams, Rcpp::List unsampledPopParams, bool useUnsamp);
RcppExport SEXP _gRandma_ssGP(SEXP baselineSEXP, SEXP mixtureSEXP, SEXP crossRecordsSEXP, SEXP baselineParamsSEXP, SEXP unsampledPopParamsSEXP, SEXP useUnsampSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type baseline(baselineSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mixture(mixtureSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type crossRecords(crossRecordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type baselineParams(baselineParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type unsampledPopParams(unsampledPopParamsSEXP);
    Rcpp::traits::input_parameter< bool >::type useUnsamp(useUnsampSEXP);
    rcpp_result_gen = Rcpp::wrap(ssGP(baseline, mixture, crossRecords, baselineParams, unsampledPopParams, useUnsamp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gRandma_ssGP", (DL_FUNC) &_gRandma_ssGP, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_gRandma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
