// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ssGP
Rcpp::DataFrame ssGP(Rcpp::NumericMatrix baseline, Rcpp::NumericMatrix mixture, Rcpp::NumericMatrix crossRecords, Rcpp::List baselineParams, Rcpp::List unsampledPopParams, Rcpp::List genotypeKey, Rcpp::List genotypeErrorRates, double saveLLR, double MIexcludeProb, bool filterLLR);
RcppExport SEXP _gRandma_ssGP(SEXP baselineSEXP, SEXP mixtureSEXP, SEXP crossRecordsSEXP, SEXP baselineParamsSEXP, SEXP unsampledPopParamsSEXP, SEXP genotypeKeySEXP, SEXP genotypeErrorRatesSEXP, SEXP saveLLRSEXP, SEXP MIexcludeProbSEXP, SEXP filterLLRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type baseline(baselineSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mixture(mixtureSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type crossRecords(crossRecordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type baselineParams(baselineParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type unsampledPopParams(unsampledPopParamsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type genotypeKey(genotypeKeySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type genotypeErrorRates(genotypeErrorRatesSEXP);
    Rcpp::traits::input_parameter< double >::type saveLLR(saveLLRSEXP);
    Rcpp::traits::input_parameter< double >::type MIexcludeProb(MIexcludeProbSEXP);
    Rcpp::traits::input_parameter< bool >::type filterLLR(filterLLRSEXP);
    rcpp_result_gen = Rcpp::wrap(ssGP(baseline, mixture, crossRecords, baselineParams, unsampledPopParams, genotypeKey, genotypeErrorRates, saveLLR, MIexcludeProb, filterLLR));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gRandma_ssGP", (DL_FUNC) &_gRandma_ssGP, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_gRandma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
