# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' pmf of Dirichlet-multinomial distribution
#' @param n the total number of draws
#' @param k a vector of the number of observations in each category
#' @param a a vector of the parameters (alpha) describing the Dirichlet
#' @noRd
#' @keywords internal
NULL

#' caluculate likelihood of parent 1, parent 2, and offspring genotypes given Mendalian inheritance
#' @param p1 parent 1 genotypes (two ints - diploid)
#' @param p2 parent 2 genotypes (two ints - diploid)
#' @param o offspring genotypes (two ints - diploid)
NULL

#' calculating llr of single-sided grandparent pair vs unrelated
#' returning a matrix of descendent, grandparentPopulation, grandparent1, grandparent2, llr
#' @param baseline baseline individuals, col1 is pop, col2 is id, cols 3... are genotypes
#' @param mixture mixture individulas col1 is id, cols 2... are genotypes
#' @param crossRecords col1 is pop, col2 is id 1, col3 is id2
#' @param baselineParams Dirichlet parameters for allele frequencies
#' @param unsampledPopParams Dirichlet parameters for allele frequencies
#' @param genotypeKey list of matrix for each locus, col1 is genotype, col2 is allele 1, col3 is allele 2
#' @param genotypeErrorRates list of matrix for each locus, rows are actual genotype, columns are observed,
#'   values are probability
#' @keywords internal
#' @noRd
#' @export
ssGP <- function(baseline, mixture, crossRecords, baselineParams, unsampledPopParams, genotypeKey, genotypeErrorRates) {
    .Call(`_gRandma_ssGP`, baseline, mixture, crossRecords, baselineParams, unsampledPopParams, genotypeKey, genotypeErrorRates)
}

