# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' pmf of Dirichlet-multinomial distribution
#' @param n the total number of draws
#' @param k a vector of the number of observations in each category
#' @param a a vector of the parameters (alpha) describing the Dirichlet
#' @noRd
#' @keywords internal
NULL

#' calculating llr of single-sided grandparent pair vs unrelated
#' returning a matrix of descendent, grandparentPopulation, grandparent1, grandparent2, llr
#' @keywords internal
#' @noRd
#' @export
ssGP <- function(baseline, mixture, crossRecords, baselineParams, unsampledPopParams, useUnsamp = FALSE) {
    .Call(`_gRandma_ssGP`, baseline, mixture, crossRecords, baselineParams, unsampledPopParams, useUnsamp)
}

